name: Build source

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash -l {0}


jobs:
  build-packages:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:

      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          miniconda-version: "latest"
          activate-environment: assembly
          channels: conda-forge
          python-version: 3.7

      - name: Install dependencies
        run: |
          conda install COMPAS=0.18.1
          pip install -r requirements-dev.txt

      - name: Lint with flake8
        run: |
          invoke lint

      - name: Test with pytest
        run: |
          invoke test

      - name: Test build docs
        run: |
          invoke docs
