name: Build docs

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: build and deploy docs
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          miniconda-version: "latest"
          activate-environment: assembly
          channels: conda-forge
          python-version: 3.7

      - name: Install dependencies
        run: |
          conda install COMPAS=0.18.1
          pip install -r requirements-dev.txt

      - name: Generate docs
        if: ${{ success() }}
        run: |
          invoke docs
          # Get branch/tag/latest name from git
          GITHUB_REF_REGEX="tags/v[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}|(pull/[0-9]+)|heads/master"
          if [[ $GITHUB_REF =~ $GITHUB_REF_REGEX ]]; then
              if [[ $BASH_REMATCH = pull* ]]; then
                  echo This is a pull request
                  FOLDER_NAME=pull_${BASH_REMATCH##*/}
              elif [[ $BASH_REMATCH = tags/* ]]; then
                  echo This is a version tag
                  FOLDER_NAME=${BASH_REMATCH##*/v}
              else
                  echo This is a commit to master branch
                  FOLDER_NAME=latest
              fi;
          fi;
          echo "Docs will be deployed to https://github.com/blockresearchgroup/compas_assembly/$FOLDER_NAME"
          mkdir -p deploy/$BRANCH_OR_TAG && mv -T dist/docs deploy/$FOLDER_NAME/

      - name: Deploy docs
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: deploy
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docVersions:
    needs: build
    name: update doc versions
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: update doc versions
        run: |
          >doc_versions.txt
          for folder in $(ls -rd */ | tr -d '/')
          do
              if [[ $folder =~ ^[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}$|^latest$ ]]
              then
                  echo ${folder}  >> doc_versions.txt
              fi
          done
          echo found available doc versions:
          cat doc_versions.txt

      - name: Deploy docs
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
